### ISSUE TITLE
Upload recording data to S3

### ISSUE THREAD

**Issue by encourage317125** [passion0805/Solid-videostreaming-recording#1]
- Use MediaRecorder function to record the Video/Audio data.
- Stream service.
- Media devices select.

**Comment by vitaliipetrov818** [comment]
@encourage317125 .
Please check this article. [https://www.wowza.com/docs/how-to-upload-recorded-media-to-an-amazon-s3-bucket-modules3upload](url)
It may help you to upload the recording data to S3 bucket.

**Comment by encourage317125** [comment]
@vitaliipetrov818 .
Thx.
